# cloudbuild.yaml
steps:
 # Step 1: Pre-check for required files
   #name: 'gcr.io/cloud-builders/gcloud'
   # entrypoint: 'bash'
    #args:
     # - '-c'
      #- |
       # echo "=== Checking required files ==="
        #for file in app.yaml package.json package-lock.json; do
         # if [ ! -f "$file" ]; then
          #  echo "❌ ERROR: Missing required file: $file"
           #exit 1
          #fi
        #done
        #echo "✅ All required files found"

  # Step 2: Debug — show current working directory & files
  #name: 'gcr.io/cloud-builders/gcloud'
    #entrypoint: 'bash'
    #args:
     # - '-c'
      #- |
       # echo "=== Current directory: $(pwd) ==="
        #echo "=== Listing files ==="
        #ls -la
  # Step 3: Deploy to App Engine Basic Environment

  - name: 'node:20'  # Uses Node.js 20.x (compatible with Vite@7+)
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        npm run build || echo "Skip if not needed"
  

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - 'app.yaml'
      - '--quiet'

logsBucket: gs://2daloop_bucket

# Optional: Extend build timeout if needed
timeout: '900s'





