steps:
  # Step 1: Pre-check for required files
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== Checking required files ==="
        for file in app.yaml package.json package-lock.json; do
          if [ ! -f "$file" ]; then
            echo "❌ ERROR: Missing required file: $file"
            exit 1
          fi
        done
        echo "✅ All required files found"

  # Step 2: Debug — show current working directory & files
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== Current directory: $(pwd) ==="
        echo "=== Listing files ==="
        ls -la

  # Step 3: Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - 'app.yaml'
      - '--quiet'

logsBucket: gs://2daloop_bucket

# Optional: Extend build timeout if needed
timeout: '900s'
